name: cryptography_flutter
description:
  A version of 'package:cryptography' that speeds up asynchronous invocations with native APIs of
  Android, iOS, and Mac OS X.
version: 2.0.1
homepage: https://github.com/dint-dev/cryptography

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  cryptography: ^2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  webcrypto: ^0.5.0

dependency_overrides:
  cryptography:
    path: ../cryptography

flutter:
  plugin:
    platforms:
      android:
        package: dev.dint.cryptography_flutter
        pluginClass: CryptographyFlutterPlugin
      ios:
        pluginClass: CryptographyFlutterPlugin
      macos:
        pluginClass: CryptographyFlutterPlugin
