name: cryptography
version: 2.0.2
homepage: https://github.com/dint-dev/cryptography
description:
  Cryptographic algorithms for encryption, digital signatures, key agreement, authentication, and
  hashing. AES, Chacha20, ED25519, X25519, and more. Web Crypto support.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  crypto: ^3.0.0
  fixnum: ^1.0.0
  js: ^0.6.3
  meta: ^1.3.0
  typed_data: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.0
